### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [component-driven/cypress-axe#126]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by reintroducing** [comment]
Since Cypress 10 is officially out, this is now blocking updates for people who don't want to see dependency issues when npm installing without using `--force` or `--legacy-peer-deps`. is this repo still being actively maintained? It looks like the last update was 5 months ago and the repo generally seems very quiet.

**Comment by reintroducing** [comment]
@sapegin is this something that is on your guys' radar? also, is this repo still actively maintained?

**Comment by bmordue** [comment]
Fixed in #130
